# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'graph_demo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for graph_demo
use_frameworks!
pod 'SwiftCharts', '~> 0.6.5'
pod 'AAInfographics'
end
